name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  location: ^4.3.0
  #mapbox_gl: ^0.16.0
  latlong: ^0.9.0
  #geolocator: ^8.0.1
  #flutter_mapbox_navigation: ^0.0.26
  #google_maps_flutter: ^2.2.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase: ^9.0.3
  cloud_firestore: ^4.4.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2



flutter:
  assets:
    - assets/
  uses-material-design: true

  # - assets/images/GRABARBERWHITE.png

  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
